### ISSUE TITLE
Getting error in line 15

### ISSUE THREAD

**Issue by rafiozzo** [stevesbrain/python-image-extractor#2]
Trying to run script and getting an error:

> File "C:\Python\extract.py", line 15
> print args.FileName
> SyntaxError: Missing parentheses in call  to 'print'. Did you mean print(args.FileName)?

Need help.

**Comment by stevesbrain** [comment]
Hi @rafiozzo - sorry for the delayed response. Please use python2 for this - the error you are getting indicates you are using python3, and I have not yet rewritten this to support python3. Thanks!
