### ISSUE TITLE
Error in line 15

### ISSUE THREAD

**Issue by Maximo19850** [stevesbrain/python-image-extractor#3]
File "C:\Python\extract.py", line 15
print args.FileName
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(args.FileName)?

the same error, pls help. TY

**Comment by stevesbrain** [comment]
Hi @Maximo19850 - sorry for the delayed response. Please use python2 for this - the error you are getting indicates you are using python3, and I have not yet rewritten this to support python3. Thanks!
