### ISSUE TITLE
The extractor gives some false positives as it uses incomplete start sequence

### ISSUE THREAD

**Issue by postpersonality** [stevesbrain/python-image-extractor#8]
Hi. Thanks for the tool!

According to wiki https://en.wikipedia.org/wiki/JPEG#:~:text=public.jpeg-,magic%20number,-ff%20d8%20ff the JPEG format has a 3-byte start sequence (magic number) whereas the extractor uses only first two bytes of it.

**Comment by stevesbrain** [comment]
Hey, thanks for the report! Correct me if I've misunderstood, but the 0xd8/ffd8 is for the Start of Image Indicator, and the 0xe0/ffe0 is the App Segment, so I think the hunting for the two bytes is correct.

The wiki link corresponds to [reference 54,](https://en.wikipedia.org/wiki/JPEG#cite_note-54) which leads to https://www.digicamsoft.com/itu/itu-t81-36.html - this references FFD8 as the SOI also, as does the original one I was looking at: https://web.archive.org/web/20120403212223/http://class.ee.iastate.edu/ee528/Reading%20material/JPEG_File_Format.pdf

However, I am by no means a JPEG file expert - happy to be corrected on this. Am I misunderstanding the information I've read? Are there downsides to the way it's currently being done? Cheers :)

**Comment by postpersonality** [comment]
Yeah the wording in the title is incorrect. You may close the issue. 
Later I realized that the second FF is a start byte for the next "frame" within jpeg. And yes, technically your solution is correct. But if I run the extractor on something that contains not only jpegs then FFD8 becomes quite common to give false positives and filtering by FFD8FF reduces false positives a lot. In my case I just improved the start sequence locally and that solved my issue.
I've tested on resource file of http://keldon.net/rftg/

**Comment by stevesbrain** [comment]
I hadn't encountered that before, so hadn't considered :) If you've noticed no negative behaviour from this local change, please feel free to send through a PR and I'll merge it in! Thanks :)

**Comment by stevesbrain** [comment]
Closed via de4ecfe63017fb82fff5de12cf6cafbf79f43f98 - thanks :)
